name: Wildberries Report Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'  # каждый день в 9:00 по МСК

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Create creds file
        run: |
          echo "${{ secrets.GOOGLE_CREDS_JSON }}" > creds/service_account.json

      - name: Run report
        env:
          SOURCE_SHEET_ID: ${{ secrets.SOURCE_SHEET_ID }}
          TARGET_SHEET_ID: ${{ secrets.TARGET_SHEET_ID }}
          GOOGLE_CREDS_PATH: creds/service_account.json
        run: python main.py
